import type { Tables } from "@/integrations/supabase/types";
import { calcularScoreLead } from "./score";

export type LeadItem = Tables<"leads">;
export type BuscaItem = Tables<"buscas">;
export type InteracaoItem = Tables<"interacoes">;

export const LEADS_DEMO: LeadItem[] = [
  {
    id: "lead-001",
    nome: "Oficina Mecânica Precision Car",
    categoria: "Oficina Mecânica",
    endereco: "Av. Tancredo Neves, 1200 - Caminho das Árvores",
    bairro: "Caminho das Árvores",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9785,
    longitude: -38.4552,
    telefone: "(71) 98844-1234",
    whatsapp_link: "https://wa.me/5571988441234",
    instagram: "precisioncar_ssa",
    facebook: "precisioncarauto",
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 47,
    place_id: "place_prec_01",
    status: "novo",
    score: 88,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Empresa conceituada na região com ótimo volume de clientes e fotos no Google, mas sem landing page própria.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "lead-002",
    nome: "Studio Bella Donna Estética",
    categoria: "Salão de Beleza",
    endereco: "Rua das Rosas, 340 - Pituba",
    bairro: "Pituba",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9961,
    longitude: -38.4612,
    telefone: "(71) 99122-8877",
    whatsapp_link: "https://wa.me/5571991228877",
    instagram: "belladonna_pituba",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 63,
    place_id: "place_bella_02",
    status: "contatado",
    score: 93,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Conversou pelo WhatsApp, dona Roberta tem interesse em agendamento online integrado.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "lead-003",
    nome: "Restaurante Sabor da Bahia",
    categoria: "Restaurante",
    endereco: "Rua do Passo, 45 - Pelourinho",
    bairro: "Pelourinho",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9714,
    longitude: -38.5088,
    telefone: "(71) 98765-4321",
    whatsapp_link: "https://wa.me/5571987654321",
    instagram: "sabordabahia_ssa",
    facebook: "sabordabahiarestaurante",
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.6,
    total_avaliacoes: 120,
    place_id: "place_sabor_03",
    status: "proposta",
    score: 90,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Enviada proposta para cardápio digital e página institucional.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "lead-004",
    nome: "Pet Care Pelos & Patas",
    categoria: "Petshop",
    endereco: "Av. Otávio Mangabeira, 2100 - Armação",
    bairro: "Armação",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9832,
    longitude: -38.4321,
    telefone: "(71) 99344-5566",
    whatsapp_link: "https://wa.me/5571993445566",
    instagram: "pelosepatas_pet",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 35,
    place_id: "place_pet_04",
    status: "fechado",
    score: 82,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Fechado contrato de criação de site e otimização de Google Meu Negócio!",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "lead-005",
    nome: "Barbearia Imperial Club",
    categoria: "Barbearia",
    endereco: "Rua Marquês de Caravelas, 88 - Barra",
    bairro: "Barra",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0089,
    longitude: -38.5284,
    telefone: "(71) 98111-2233",
    whatsapp_link: "https://wa.me/5571981112233",
    instagram: "imperialbarber_ssa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 88,
    place_id: "place_barber_05",
    status: "novo",
    score: 95,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Barbearia movimentada na Barra sem página própria. Alta prioridade.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "lead-006",
    nome: "Santos Imóveis & Consultoria",
    categoria: "Corretor de Imóveis",
    endereco: "Alameda das Espatódeas, 500 - Itaigara",
    bairro: "Itaigara",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9899,
    longitude: -38.4725,
    telefone: "(71) 99888-7766",
    whatsapp_link: "https://wa.me/5571998887766",
    instagram: null,
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.5,
    total_avaliacoes: 14,
    place_id: "place_imob_06",
    status: "novo",
    score: 72,
    origem: "manual",
    responsavel_id: null,
    observacoes: "Corretor autônomo atuando em condomínios de alto padrão.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "lead-007",
    nome: "Dra. Camila Odontologia Integrada",
    categoria: "Dentista",
    endereco: "Av. Anita Garibaldi, 1815 - Ondina",
    bairro: "Ondina",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0034,
    longitude: -38.5021,
    telefone: "(71) 98777-3344",
    whatsapp_link: "https://wa.me/5571987773344",
    instagram: "dracamilasouza_odonto",
    facebook: null,
    site_url: "https://dracamilasouza.com.br",
    tem_site: true,
    avaliacao_google: 5.0,
    total_avaliacoes: 42,
    place_id: "place_dent_07",
    status: "recusado",
    score: 35,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Já possui site próprio responsivo recente.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
  {
    id: "lead-008",
    nome: "Academia Iron Force Fitness",
    categoria: "Academia",
    endereco: "Rua Silveira Martins, 780 - Cabula",
    bairro: "Cabula",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9567,
    longitude: -38.4688,
    telefone: "(71) 99222-1199",
    whatsapp_link: "https://wa.me/5571992221199",
    instagram: "ironforcesalvador",
    facebook: "ironforcecabula",
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 95,
    place_id: "place_gym_08",
    status: "contatado",
    score: 94,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Muito procurada no Cabula. Gostaram da ideia de tabela de planos no site.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "lead-009",
    nome: "Hamburgueria Artesanal The Burguer Lab",
    categoria: "Restaurante",
    endereco: "Rua Fonte do Boi, 112 - Rio Vermelho",
    bairro: "Rio Vermelho",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0135,
    longitude: -38.4905,
    telefone: "(71) 99455-2233",
    whatsapp_link: "https://wa.me/5571994552233",
    instagram: "theburguerlab_ssa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 140,
    place_id: "place_burg_09",
    status: "novo",
    score: 96,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Grande fluxo de pedidos no Rio Vermelho, sem site ou cardápio online indexado.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
  {
    id: "lead-010",
    nome: "Clínica Veterinária Pet Vitta",
    categoria: "Clínica Veterinária",
    endereco: "Av. Paulo VI, 850 - Pituba",
    bairro: "Pituba",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9880,
    longitude: -38.4590,
    telefone: "(71) 98788-3344",
    whatsapp_link: "https://wa.me/5571987883344",
    instagram: "petvitta_vet",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 78,
    place_id: "place_vet_10",
    status: "novo",
    score: 92,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Atendimento 24h na Pituba sem portal de plantão ou agendamento.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
  },
  {
    id: "lead-011",
    nome: "Pizzaria Don Corleone Napoletana",
    categoria: "Restaurante",
    endereco: "Rua do Meio, 25 - Rio Vermelho",
    bairro: "Rio Vermelho",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0110,
    longitude: -38.4870,
    telefone: "(71) 99123-4567",
    whatsapp_link: "https://wa.me/5571991234567",
    instagram: "doncorleone_pizza",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 110,
    place_id: "place_piz_11",
    status: "novo",
    score: 89,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Forno a lenha de tradição no Rio Vermelho buscando delivery direto.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
  },
  {
    id: "lead-012",
    nome: "Autoescola Primeira Marcha",
    categoria: "Autoescola",
    endereco: "Rua Jayme Sapolnik, 150 - Imbuí",
    bairro: "Imbuí",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9688,
    longitude: -38.4312,
    telefone: "(71) 98855-6677",
    whatsapp_link: "https://wa.me/5571988556677",
    instagram: "autoescolaprimeiramarcha",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.6,
    total_avaliacoes: 52,
    place_id: "place_auto_12",
    status: "contatado",
    score: 87,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Interesse em simulador de matrícula e portal do aluno.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
  {
    id: "lead-013",
    nome: "Boutique L'Amour Moda Feminina",
    categoria: "Loja de Roupas",
    endereco: "Av. Sete de Setembro, 2400 - Vitória",
    bairro: "Vitória",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9980,
    longitude: -38.5250,
    telefone: "(71) 99666-4433",
    whatsapp_link: "https://wa.me/5571996664433",
    instagram: "lamour_boutiquessa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 38,
    place_id: "place_bout_13",
    status: "novo",
    score: 91,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Loja de luxo no Corredor da Vitória sem e-commerce ou catálogo online.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
  },
  {
    id: "lead-014",
    nome: "Centro Automotivo Master Car",
    categoria: "Oficina Mecânica",
    endereco: "Rua Dom João VI, 400 - Brotas",
    bairro: "Brotas",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9850,
    longitude: -38.4900,
    telefone: "(71) 98711-9988",
    whatsapp_link: "https://wa.me/5571987119988",
    instagram: "mastercar_brotas",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.5,
    total_avaliacoes: 64,
    place_id: "place_mec_14",
    status: "novo",
    score: 85,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Oficina de injeção e suspensão em Brotas com alto tráfego local.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
  },
  {
    id: "lead-015",
    nome: "Bar & Espeto Stella Sunset",
    categoria: "Restaurante",
    endereco: "Alameda Praia de Guarajuba, 80 - Stella Maris",
    bairro: "Stella Maris",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9422,
    longitude: -38.3312,
    telefone: "(71) 99233-1122",
    whatsapp_link: "https://wa.me/5571992331122",
    instagram: "stellasunset_bar",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.6,
    total_avaliacoes: 92,
    place_id: "place_bar_15",
    status: "proposta",
    score: 88,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Bar praiano em Stella Maris com música ao vivo aos fins de semana.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
  },
  {
    id: "lead-016",
    nome: "Barbearia Vintage Navalha de Ouro",
    categoria: "Barbearia",
    endereco: "Rua Miguel Burnier, 45 - Barra",
    bairro: "Barra",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0060,
    longitude: -38.5310,
    telefone: "(71) 98877-6655",
    whatsapp_link: "https://wa.me/5571988776655",
    instagram: "navalhadouro_barra",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 74,
    place_id: "place_barb_16",
    status: "novo",
    score: 93,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Cortes clássicos e barboterapia na Barra.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
  },
  {
    id: "lead-017",
    nome: "Salão & Spa Cabelo & Arte",
    categoria: "Salão de Beleza",
    endereco: "Rua Afonso Celso, 200 - Barra",
    bairro: "Barra",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0105,
    longitude: -38.5260,
    telefone: "(71) 99199-4455",
    whatsapp_link: "https://wa.me/5571991994455",
    instagram: "cabeloearte_ssa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 56,
    place_id: "place_sal_17",
    status: "contatado",
    score: 90,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Especialista em mechas e noivas sem portfólio web.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(),
  },
  {
    id: "lead-018",
    nome: "CrossFit Pituba Force",
    categoria: "Academia",
    endereco: "Av. Manoel Dias da Silva, 1400 - Pituba",
    bairro: "Pituba",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9990,
    longitude: -38.4680,
    telefone: "(71) 99311-8899",
    whatsapp_link: "https://wa.me/5571993118899",
    instagram: "crossfitpitubaforce",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 130,
    place_id: "place_cross_18",
    status: "novo",
    score: 97,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Box de CrossFit com alta adesão na Pituba, sem página institucional de planos.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 34).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 34).toISOString(),
  },
  {
    id: "lead-019",
    nome: "Restaurante Tempero da Graça",
    categoria: "Restaurante",
    endereco: "Rua da Graça, 180 - Graça",
    bairro: "Graça",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9950,
    longitude: -38.5200,
    telefone: "(71) 98733-2211",
    whatsapp_link: "https://wa.me/5571987332211",
    instagram: "temperodagraca",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 85,
    place_id: "place_rest_19",
    status: "novo",
    score: 86,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Buffet executivo conceituado na Graça.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
  {
    id: "lead-020",
    nome: "Clínica de Estética & Laser Derma Bella",
    categoria: "Salão de Beleza",
    endereco: "Rua Ewerton Visco, 290 - Caminho das Árvores",
    bairro: "Caminho das Árvores",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9810,
    longitude: -38.4520,
    telefone: "(71) 99188-7744",
    whatsapp_link: "https://wa.me/5571991887744",
    instagram: "dermabella_estetica",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 5.0,
    total_avaliacoes: 48,
    place_id: "place_derm_20",
    status: "novo",
    score: 94,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Depilação a laser e harmonização facial.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 38).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 38).toISOString(),
  },
  {
    id: "lead-021",
    nome: "Pet Boutique & Banho AuAu Elegance",
    categoria: "Petshop",
    endereco: "Rua Bahia, 512 - Pituba",
    bairro: "Pituba",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9930,
    longitude: -38.4630,
    telefone: "(71) 98822-3311",
    whatsapp_link: "https://wa.me/5571988223311",
    instagram: "auauelegance_pet",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 61,
    place_id: "place_pet_21",
    status: "contatado",
    score: 89,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Banho e tosa com leva e traz na Pituba.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
  },
  {
    id: "lead-022",
    nome: "Oficina Eletro Mecânica Bahia Auto",
    categoria: "Oficina Mecânica",
    endereco: "Av. Dom João VI, 1100 - Brotas",
    bairro: "Brotas",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9870,
    longitude: -38.4860,
    telefone: "(71) 99244-8833",
    whatsapp_link: "https://wa.me/5571992448833",
    instagram: "bahiaauto_eletrica",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.6,
    total_avaliacoes: 43,
    place_id: "place_elet_22",
    status: "novo",
    score: 83,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Auto elétrica, ar-condicionado e bateria.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 42).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 42).toISOString(),
  },
  {
    id: "lead-023",
    nome: "Dra. Juliana Vasconcelos Odonto",
    categoria: "Dentista",
    endereco: "Av. ACM, 2501 - Itaigara",
    bairro: "Itaigara",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9860,
    longitude: -38.4750,
    telefone: "(71) 98799-5566",
    whatsapp_link: "https://wa.me/5571987995566",
    instagram: "drajulianavasconcelos",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 37,
    place_id: "place_dent_23",
    status: "novo",
    score: 91,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Ortodontia e clareamento dental.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 44).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 44).toISOString(),
  },
  {
    id: "lead-024",
    nome: "Escritório Contábil Salvador Express",
    categoria: "Contabilidade",
    endereco: "Rua Alceu Amoroso Lima, 140 - Caminho das Árvores",
    bairro: "Caminho das Árvores",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9760,
    longitude: -38.4580,
    telefone: "(71) 98122-3344",
    whatsapp_link: "https://wa.me/5571981223344",
    instagram: "contabilsalvador",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 29,
    place_id: "place_cont_24",
    status: "novo",
    score: 86,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Abertura de empresas e assessoria fiscal para MEI e ME.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 46).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 46).toISOString(),
  },
  {
    id: "lead-025",
    nome: "Parrilla & Chopp Costa Azul",
    categoria: "Restaurante",
    endereco: "Rua Arthur de Azevêdo Machado, 780 - Costa Azul",
    bairro: "Costa Azul",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9870,
    longitude: -38.4450,
    telefone: "(71) 99655-3322",
    whatsapp_link: "https://wa.me/5571996553322",
    instagram: "parrillacostaazul",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 115,
    place_id: "place_parr_25",
    status: "novo",
    score: 95,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Carnes nobres na brasa e chopp artesanal no Costa Azul.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "lead-026",
    nome: "Sorveteria & Açaí Solar da Barra",
    categoria: "Restaurante",
    endereco: "Av. Oceânica, 520 - Barra",
    bairro: "Barra",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0115,
    longitude: -38.5320,
    telefone: "(71) 98833-9900",
    whatsapp_link: "https://wa.me/5571988339900",
    instagram: "solardabarra_acai",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 160,
    place_id: "place_sorv_26",
    status: "novo",
    score: 97,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Ponto nobre em frente ao Farol da Barra com imenso fluxo de turistas.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
  },
  {
    id: "lead-027",
    nome: "Studio Pilates & Fisioterapia Viver Bem",
    categoria: "Academia",
    endereco: "Rua Marquês de Monte Santo, 310 - Rio Vermelho",
    bairro: "Rio Vermelho",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0125,
    longitude: -38.4840,
    telefone: "(71) 99177-6655",
    whatsapp_link: "https://wa.me/5571991776655",
    instagram: "pilatesviverbem_ssa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 45,
    place_id: "place_pil_27",
    status: "contatado",
    score: 91,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Studio com 3 fisioterapeutas com agenda cheia querendo sistema web.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 52).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 52).toISOString(),
  },
  {
    id: "lead-028",
    nome: "Auto Center Pneus & Alinhamento Pituba",
    categoria: "Oficina Mecânica",
    endereco: "Av. Otávio Mangabeira, 1500 - Pituba",
    bairro: "Pituba",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9985,
    longitude: -38.4570,
    telefone: "(71) 98744-1122",
    whatsapp_link: "https://wa.me/5571987441122",
    instagram: "autocenterpituba",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 82,
    place_id: "place_pneu_28",
    status: "novo",
    score: 89,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Troca de óleo, balanceamento e pneus na orla da Pituba.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 54).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 54).toISOString(),
  },
  {
    id: "lead-029",
    nome: "Dra. Renata Vasconcellos Dermatologia",
    categoria: "Dentista",
    endereco: "Av. Tancredo Neves, 2227 - Caminho das Árvores",
    bairro: "Caminho das Árvores",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9800,
    longitude: -38.4500,
    telefone: "(71) 99388-9900",
    whatsapp_link: "https://wa.me/5571993889900",
    instagram: "drarenatavasconcellos",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 5.0,
    total_avaliacoes: 53,
    place_id: "place_derm_29",
    status: "proposta",
    score: 95,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Consultório no Salvador Trade Center sem site próprio.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 56).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 56).toISOString(),
  },
  {
    id: "lead-030",
    nome: "Barbearia Don Barber Club",
    categoria: "Barbearia",
    endereco: "Rua do Salitre, 88 - Patamares",
    bairro: "Patamares",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9620,
    longitude: -38.3980,
    telefone: "(71) 98133-7788",
    whatsapp_link: "https://wa.me/5571981337788",
    instagram: "donbarber_patamares",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 67,
    place_id: "place_barb_30",
    status: "novo",
    score: 92,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Barbearia em Patamares com sinuca e chopp.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 58).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 58).toISOString(),
  },
  {
    id: "lead-031",
    nome: "Padaria & Delicatessen Pão Real",
    categoria: "Restaurante",
    endereco: "Rua Pernambuco, 340 - Pituba",
    bairro: "Pituba",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9970,
    longitude: -38.4625,
    telefone: "(71) 99211-4433",
    whatsapp_link: "https://wa.me/5571992114433",
    instagram: "paoreal_pituba",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 185,
    place_id: "place_pad_31",
    status: "novo",
    score: 93,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Pães artesanais, café da manhã e encomendas.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
  },
  {
    id: "lead-032",
    nome: "Centro de Estética Corpore Sano",
    categoria: "Salão de Beleza",
    endereco: "Alameda dos Umbuzeiros, 450 - Caminho das Árvores",
    bairro: "Caminho das Árvores",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9820,
    longitude: -38.4590,
    telefone: "(71) 98866-5544",
    whatsapp_link: "https://wa.me/5571988665544",
    instagram: "corporesano_estetica",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 58,
    place_id: "place_corp_32",
    status: "contatado",
    score: 90,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Massoterapia e drenagem linfática com ótima carteira de clientes.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 62).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 62).toISOString(),
  },
  {
    id: "lead-033",
    nome: "Academia Smart Life Fitness",
    categoria: "Academia",
    endereco: "Av. Jorge Amado, 890 - Imbuí",
    bairro: "Imbuí",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9660,
    longitude: -38.4350,
    telefone: "(71) 99422-7788",
    whatsapp_link: "https://wa.me/5571994227788",
    instagram: "smartlifefitness_ssa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.6,
    total_avaliacoes: 104,
    place_id: "place_acad_33",
    status: "novo",
    score: 88,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Musculação, fitdance e funcional no Imbuí.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 64).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 64).toISOString(),
  },
  {
    id: "lead-034",
    nome: "Restaurante Mar & Brasa Frutos do Mar",
    categoria: "Restaurante",
    endereco: "Largo de Santana, 12 - Rio Vermelho",
    bairro: "Rio Vermelho",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0140,
    longitude: -38.4920,
    telefone: "(71) 98722-6655",
    whatsapp_link: "https://wa.me/5571987226655",
    instagram: "marebrasa_ssa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 175,
    place_id: "place_mar_34",
    status: "novo",
    score: 96,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Moquecas tradicionais e peixes grelhados na brasa no Largo de Santana.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 66).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 66).toISOString(),
  },
  {
    id: "lead-035",
    nome: "Pet Center Hospital & Diagnóstico",
    categoria: "Clínica Veterinária",
    endereco: "Av. Cardeal da Silva, 450 - Federação",
    bairro: "Federação",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0010,
    longitude: -38.5110,
    telefone: "(71) 99155-3344",
    whatsapp_link: "https://wa.me/5571991553344",
    instagram: "petcenter_federacao",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 86,
    place_id: "place_hosp_35",
    status: "novo",
    score: 94,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Cirurgias e exames de imagem veterinários 24 horas.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 68).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 68).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — SÃO PAULO / SP
  // =========================================================================
  {
    id: "lead-sp-01",
    nome: "Bistrô Paulista Gourmet",
    categoria: "Restaurante",
    endereco: "Rua dos Pinheiros, 780 - Pinheiros",
    bairro: "Pinheiros",
    cidade: "São Paulo",
    estado: "SP",
    latitude: -23.5652,
    longitude: -46.6890,
    telefone: "(11) 98712-3456",
    whatsapp_link: "https://wa.me/5511987123456",
    instagram: "bistropinheiros_sp",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 145,
    place_id: "gp_sp_pinheiros_01",
    status: "novo",
    score: 95,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Restaurante movimentado em Pinheiros sem cardápio digital ou site próprio.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "lead-sp-02",
    nome: "Clínica Odonto Moema Premium",
    categoria: "Dentista",
    endereco: "Av. Moema, 450 - Moema",
    bairro: "Moema",
    cidade: "São Paulo",
    estado: "SP",
    latitude: -23.6035,
    longitude: -46.6625,
    telefone: "(11) 99233-4455",
    whatsapp_link: "https://wa.me/5511992334455",
    instagram: "odontomoema_oficial",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 88,
    place_id: "gp_sp_moema_02",
    status: "contatado",
    score: 92,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Dra. Patrícia deseja sistema de agendamento integrado ao WhatsApp.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
  {
    id: "lead-sp-03",
    nome: "Barbearia Itaim Vintage",
    categoria: "Barbearia",
    endereco: "Rua Joaquim Floriano, 240 - Itaim Bibi",
    bairro: "Itaim Bibi",
    cidade: "São Paulo",
    estado: "SP",
    latitude: -23.5845,
    longitude: -46.6780,
    telefone: "(11) 97188-9900",
    whatsapp_link: "https://wa.me/5511971889900",
    instagram: "itaim_vintage_barber",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 110,
    place_id: "gp_sp_itaim_03",
    status: "novo",
    score: 89,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Barbearia conceito no Itaim Bibi com alto fluxo.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — RIO DE JANEIRO / RJ
  // =========================================================================
  {
    id: "lead-rj-01",
    nome: "Studio Estética Copacabana",
    categoria: "Clínica de Estética",
    endereco: "Av. Nossa Senhora de Copacabana, 820 - Copacabana",
    bairro: "Copacabana",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    latitude: -22.9710,
    longitude: -43.1870,
    telefone: "(21) 98877-6655",
    whatsapp_link: "https://wa.me/5521988776655",
    instagram: "esteticacopa_rio",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 95,
    place_id: "gp_rj_copa_01",
    status: "proposta",
    score: 94,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Proposta enviada para criação de catálogo e agendamento.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "lead-rj-02",
    nome: "Pet Boutique Ipanema",
    categoria: "Petshop",
    endereco: "Rua Visconde de Pirajá, 310 - Ipanema",
    bairro: "Ipanema",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    latitude: -22.9840,
    longitude: -43.2040,
    telefone: "(21) 97233-1122",
    whatsapp_link: "https://wa.me/5521972331122",
    instagram: "petboutique_ipanema",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 72,
    place_id: "gp_rj_ipanema_02",
    status: "novo",
    score: 91,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Pet shop de luxo em Ipanema sem loja virtual.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — BELO HORIZONTE / MG
  // =========================================================================
  {
    id: "lead-mg-01",
    nome: "Oficina Savassi Motors",
    categoria: "Oficina Mecânica",
    endereco: "Rua Fernandes Tourinho, 520 - Savassi",
    bairro: "Savassi",
    cidade: "Belo Horizonte",
    estado: "MG",
    latitude: -19.9385,
    longitude: -43.9350,
    telefone: "(31) 99888-7744",
    whatsapp_link: "https://wa.me/5531998887744",
    instagram: "savassimotors_bh",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 64,
    place_id: "gp_mg_savassi_01",
    status: "novo",
    score: 87,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Centro automotivo multimarcas na Savassi.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 15).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 15).toISOString(),
  },
  {
    id: "lead-mg-02",
    nome: "Pizzaria Tradição Mineira",
    categoria: "Pizzaria",
    endereco: "Rua Curitiba, 1420 - Lourdes",
    bairro: "Lourdes",
    cidade: "Belo Horizonte",
    estado: "MG",
    latitude: -19.9290,
    longitude: -43.9440,
    telefone: "(31) 98455-2233",
    whatsapp_link: "https://wa.me/5531984552233",
    instagram: "tradicamg_pizza",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 130,
    place_id: "gp_mg_lourdes_02",
    status: "novo",
    score: 93,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Pizzaria artesanal conceituada no bairro de Lourdes.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — CURITIBA / PR
  // =========================================================================
  {
    id: "lead-pr-01",
    nome: "Academia Batel Fit Concept",
    categoria: "Academia",
    endereco: "Av. do Batel, 1550 - Batel",
    bairro: "Batel",
    cidade: "Curitiba",
    estado: "PR",
    latitude: -25.4430,
    longitude: -49.2890,
    telefone: "(41) 99122-3344",
    whatsapp_link: "https://wa.me/5541991223344",
    instagram: "batelfit_cwb",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 115,
    place_id: "gp_pr_batel_01",
    status: "fechado",
    score: 96,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Cliente contratou landing page de planos e matrículas online.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — BRASÍLIA / DF
  // =========================================================================
  {
    id: "lead-df-01",
    nome: "Hamburgueria Capital Prime",
    categoria: "Hamburgueria",
    endereco: "CLS 405 Bloco C - Asa Sul",
    bairro: "Asa Sul",
    cidade: "Brasília",
    estado: "DF",
    latitude: -15.8210,
    longitude: -47.9040,
    telefone: "(61) 98544-7788",
    whatsapp_link: "https://wa.me/5561985447788",
    instagram: "capitalprime_bsb",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 160,
    place_id: "gp_df_asasul_01",
    status: "novo",
    score: 95,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Hamburgueria artesanal de alto movimento na 405 Sul sem site próprio.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — PORTO ALEGRE / RS
  // =========================================================================
  {
    id: "lead-rs-01",
    nome: "Clínica Veterinária Moinhos",
    categoria: "Clínica Veterinária",
    endereco: "Rua Padre Chagas, 280 - Moinhos de Vento",
    bairro: "Moinhos de Vento",
    cidade: "Porto Alegre",
    estado: "RS",
    latitude: -30.0260,
    longitude: -51.2030,
    telefone: "(51) 99311-5566",
    whatsapp_link: "https://wa.me/5551993115566",
    instagram: "vetmoinhos_poa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 78,
    place_id: "gp_rs_moinhos_01",
    status: "novo",
    score: 92,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Atendimento clínico e vacinas em Moinhos de Vento.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 35).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 35).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — FLORIANÓPOLIS / SC
  // =========================================================================
  {
    id: "lead-sc-01",
    nome: "Espaço Bem Estar Lagoa",
    categoria: "Salão de Beleza",
    endereco: "Rua Henrique Veras do Nascimento, 190 - Lagoa da Conceição",
    bairro: "Lagoa da Conceição",
    cidade: "Florianópolis",
    estado: "SC",
    latitude: -27.6040,
    longitude: -48.4680,
    telefone: "(48) 99655-4433",
    whatsapp_link: "https://wa.me/5548996554433",
    instagram: "bemestarlagoa_floripa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 52,
    place_id: "gp_sc_lagoa_01",
    status: "novo",
    score: 89,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Salão e terapias capilares na Lagoa da Conceição.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 42).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 42).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — RECIFE / PE
  // =========================================================================
  {
    id: "lead-pe-01",
    nome: "Restaurante Maré Boa Viagem",
    categoria: "Restaurante",
    endereco: "Av. Boa Viagem, 3200 - Boa Viagem",
    bairro: "Boa Viagem",
    cidade: "Recife",
    estado: "PE",
    latitude: -8.1180,
    longitude: -34.8970,
    telefone: "(81) 98744-1122",
    whatsapp_link: "https://wa.me/5581987441122",
    instagram: "mareboaviagem_recife",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 140,
    place_id: "gp_pe_boaviagem_01",
    status: "novo",
    score: 93,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Frutos do mar e cozinha regional à beira-mar de Boa Viagem.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — FORTALEZA / CE
  // =========================================================================
  {
    id: "lead-ce-01",
    nome: "Clínica Dermatológica Meireles",
    categoria: "Clínica de Estética",
    endereco: "Av. Dom Luís, 600 - Aldeota",
    bairro: "Aldeota",
    cidade: "Fortaleza",
    estado: "CE",
    latitude: -3.7340,
    longitude: -38.4980,
    telefone: "(85) 99133-8877",
    whatsapp_link: "https://wa.me/5585991338877",
    instagram: "dermato_meireles_for",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 105,
    place_id: "gp_ce_meireles_01",
    status: "novo",
    score: 95,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Procedimentos estéticos faciais e corporais na Aldeota/Meireles.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
  },

  // =========================================================================
  // LEADS EXPANDIDOS — GOIÂNIA / GO
  // =========================================================================
  {
    id: "lead-go-01",
    nome: "Barbearia Marista Club",
    categoria: "Barbearia",
    endereco: "Rua 146, 320 - Setor Marista",
    bairro: "Setor Marista",
    cidade: "Goiânia",
    estado: "GO",
    latitude: -16.7020,
    longitude: -49.2620,
    telefone: "(62) 98222-3311",
    whatsapp_link: "https://wa.me/5562982223311",
    instagram: "maristaclub_gyn",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 89,
    place_id: "gp_go_marista_01",
    status: "novo",
    score: 90,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Barbearia premium com espaço de bar e convivência no Setor Marista.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(),
  },
];

export const BUSCAS_DEMO: BuscaItem[] = [
  {
    id: "busca-001",
    termo_busca: "oficina mecanica salvador caminho das arvores",
    categoria: "Oficina Mecânica",
    regiao: "Salvador - Caminho das Árvores",
    raio_km: 5,
    total_resultados: 18,
    total_sem_site: 13,
    executada_por: null,
    criada_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "busca-002",
    termo_busca: "salao de beleza pituba",
    categoria: "Salão de Beleza",
    regiao: "Salvador - Pituba",
    raio_km: 3,
    total_resultados: 24,
    total_sem_site: 19,
    executada_por: null,
    criada_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "busca-003",
    termo_busca: "barbearia barra salvador",
    categoria: "Barbearia",
    regiao: "Salvador - Barra",
    raio_km: 4,
    total_resultados: 15,
    total_sem_site: 11,
    executada_por: null,
    criada_em: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
];

export const INTERACOES_DEMO: InteracaoItem[] = [
  {
    id: "int-001",
    lead_id: "lead-002",
    tipo: "whatsapp",
    descricao: "Primeiro contato comercial apresentando portfólio de salões parceiros.",
    resultado: "Dona Roberta respondeu com interesse em agendamento online.",
    usuario_id: null,
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "int-002",
    lead_id: "lead-003",
    tipo: "ligacao",
    descricao: "Ligação para falar com o gerente sobre presença digital no Pelourinho.",
    resultado: "Gerente pediu para enviar apresentação e proposta via WhatsApp.",
    usuario_id: null,
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "int-003",
    lead_id: "lead-004",
    tipo: "visita",
    descricao: "Reunião presencial para validação do escopo da landing page do Petshop.",
    resultado: "Contrato fechado com sucesso!",
    usuario_id: null,
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];
