import type { Tables } from "@/integrations/supabase/types";
import { calcularScoreLead } from "./score";

export type LeadItem = Tables<"leads">;
export type BuscaItem = Tables<"buscas">;
export type InteracaoItem = Tables<"interacoes">;

export const LEADS_DEMO: LeadItem[] = [
  {
    id: "lead-001",
    nome: "Oficina Mecânica Precision Car",
    categoria: "Oficina Mecânica",
    endereco: "Av. Tancredo Neves, 1200 - Caminho das Árvores",
    bairro: "Caminho das Árvores",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9785,
    longitude: -38.4552,
    telefone: "(71) 98844-1234",
    whatsapp_link: "https://wa.me/5571988441234",
    instagram: "precisioncar_ssa",
    facebook: "precisioncarauto",
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.8,
    total_avaliacoes: 47,
    place_id: "place_prec_01",
    status: "novo",
    score: 88,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Empresa conceituada na região com ótimo volume de clientes e fotos no Google, mas sem landing page própria.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "lead-002",
    nome: "Studio Bella Donna Estética",
    categoria: "Salão de Beleza",
    endereco: "Rua das Rosas, 340 - Pituba",
    bairro: "Pituba",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9961,
    longitude: -38.4612,
    telefone: "(71) 99122-8877",
    whatsapp_link: "https://wa.me/5571991228877",
    instagram: "belladonna_pituba",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 63,
    place_id: "place_bella_02",
    status: "contatado",
    score: 93,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Conversou pelo WhatsApp, dona Roberta tem interesse em agendamento online integrado.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "lead-003",
    nome: "Restaurante Sabor da Bahia",
    categoria: "Restaurante",
    endereco: "Rua do Passo, 45 - Pelourinho",
    bairro: "Pelourinho",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9714,
    longitude: -38.5088,
    telefone: "(71) 98765-4321",
    whatsapp_link: "https://wa.me/5571987654321",
    instagram: "sabordabahia_ssa",
    facebook: "sabordabahiarestaurante",
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.6,
    total_avaliacoes: 120,
    place_id: "place_sabor_03",
    status: "proposta",
    score: 90,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Enviada proposta para cardápio digital e página institucional.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "lead-004",
    nome: "Pet Care Pelos & Patas",
    categoria: "Petshop",
    endereco: "Av. Otávio Mangabeira, 2100 - Armação",
    bairro: "Armação",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9832,
    longitude: -38.4321,
    telefone: "(71) 99344-5566",
    whatsapp_link: "https://wa.me/5571993445566",
    instagram: "pelosepatas_pet",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 35,
    place_id: "place_pet_04",
    status: "fechado",
    score: 82,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Fechado contrato de criação de site e otimização de Google Meu Negócio!",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "lead-005",
    nome: "Barbearia Imperial Club",
    categoria: "Barbearia",
    endereco: "Rua Marquês de Caravelas, 88 - Barra",
    bairro: "Barra",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0089,
    longitude: -38.5284,
    telefone: "(71) 98111-2233",
    whatsapp_link: "https://wa.me/5571981112233",
    instagram: "imperialbarber_ssa",
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.9,
    total_avaliacoes: 88,
    place_id: "place_barber_05",
    status: "novo",
    score: 95,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Barbearia movimentada na Barra sem página própria. Alta prioridade.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "lead-006",
    nome: "Santos Imóveis & Consultoria",
    categoria: "Corretor de Imóveis",
    endereco: "Alameda das Espatódeas, 500 - Itaigara",
    bairro: "Itaigara",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9899,
    longitude: -38.4725,
    telefone: "(71) 99888-7766",
    whatsapp_link: "https://wa.me/5571998887766",
    instagram: null,
    facebook: null,
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.5,
    total_avaliacoes: 14,
    place_id: "place_imob_06",
    status: "novo",
    score: 72,
    origem: "manual",
    responsavel_id: null,
    observacoes: "Corretor autônomo atuando em condomínios de alto padrão.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "lead-007",
    nome: "Dra. Camila Odontologia Integrada",
    categoria: "Dentista",
    endereco: "Av. Anita Garibaldi, 1815 - Ondina",
    bairro: "Ondina",
    cidade: "Salvador",
    estado: "BA",
    latitude: -13.0034,
    longitude: -38.5021,
    telefone: "(71) 98777-3344",
    whatsapp_link: "https://wa.me/5571987773344",
    instagram: "dracamilasouza_odonto",
    facebook: null,
    site_url: "https://dracamilasouza.com.br",
    tem_site: true,
    avaliacao_google: 5.0,
    total_avaliacoes: 42,
    place_id: "place_dent_07",
    status: "recusado",
    score: 35,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Já possui site próprio responsivo recente.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
  {
    id: "lead-008",
    nome: "Academia Iron Force Fitness",
    categoria: "Academia",
    endereco: "Rua Silveira Martins, 780 - Cabula",
    bairro: "Cabula",
    cidade: "Salvador",
    estado: "BA",
    latitude: -12.9567,
    longitude: -38.4688,
    telefone: "(71) 99222-1199",
    whatsapp_link: "https://wa.me/5571992221199",
    instagram: "ironforcesalvador",
    facebook: "ironforcecabula",
    site_url: null,
    tem_site: false,
    avaliacao_google: 4.7,
    total_avaliacoes: 95,
    place_id: "place_gym_08",
    status: "contatado",
    score: 94,
    origem: "google_places",
    responsavel_id: null,
    observacoes: "Muito procurada no Cabula. Gostaram da ideia de tabela de planos no site.",
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    atualizado_em: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
];

export const BUSCAS_DEMO: BuscaItem[] = [
  {
    id: "busca-001",
    termo_busca: "oficina mecanica salvador caminho das arvores",
    categoria: "Oficina Mecânica",
    regiao: "Salvador - Caminho das Árvores",
    raio_km: 5,
    total_resultados: 18,
    total_sem_site: 13,
    executada_por: null,
    criada_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "busca-002",
    termo_busca: "salao de beleza pituba",
    categoria: "Salão de Beleza",
    regiao: "Salvador - Pituba",
    raio_km: 3,
    total_resultados: 24,
    total_sem_site: 19,
    executada_por: null,
    criada_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "busca-003",
    termo_busca: "barbearia barra salvador",
    categoria: "Barbearia",
    regiao: "Salvador - Barra",
    raio_km: 4,
    total_resultados: 15,
    total_sem_site: 11,
    executada_por: null,
    criada_em: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
];

export const INTERACOES_DEMO: InteracaoItem[] = [
  {
    id: "int-001",
    lead_id: "lead-002",
    tipo: "whatsapp",
    descricao: "Primeiro contato comercial apresentando portfólio de salões parceiros.",
    resultado: "Dona Roberta respondeu com interesse em agendamento online.",
    usuario_id: null,
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "int-002",
    lead_id: "lead-003",
    tipo: "ligacao",
    descricao: "Ligação para falar com o gerente sobre presença digital no Pelourinho.",
    resultado: "Gerente pediu para enviar apresentação e proposta via WhatsApp.",
    usuario_id: null,
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "int-003",
    lead_id: "lead-004",
    tipo: "visita",
    descricao: "Reunião presencial para validação do escopo da landing page do Petshop.",
    resultado: "Contrato fechado com sucesso!",
    usuario_id: null,
    criado_em: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];
